### ISSUE TITLE
Process.io_counters() fails randomly on Linux with "need more than 1 value to unpack"

### ISSUE THREAD

**Issue by qris** [giampaolo/psutil#1004]
This happened once so far, at process startup, so it seems to be random:

```
Traceback (most recent call last):
...
    return self._process.io_counters()
  File "/remote/install/sw/external/20170403-0-64/lib/python2.7/site-packages/psutil-5.2.1-py2.7-linux-x86_64.egg/psutil/__init__.py", line 787, in io_counters
    return self._proc.io_counters()
  File "/remote/install/sw/external/20170403-0-64/lib/python2.7/site-packages/psutil-5.2.1-py2.7-linux-x86_64.egg/psutil/_pslinux.py", line 1320, in wrapper
    return fun(self, *args, **kwargs)
  File "/remote/install/sw/external/20170403-0-64/lib/python2.7/site-packages/psutil-5.2.1-py2.7-linux-x86_64.egg/psutil/_pslinux.py", line 1451, in io_counters
    name, value = line.split(b': ')
ValueError: need more than 1 value to unpack
```

It looks like a Linux bug, because if I cat `/proc/self/io` (a freshly started process) then I see a blank line at the end (which could cause this error):

```
$ cat /proc/self/io
rchar: 2012
wchar: 0
syscr: 7
syscw: 0
read_bytes: 0
write_bytes: 0
cancelled_write_bytes: 0

```

Whereas if I look at an established process, I see no blank line at the end:

```
$ cat /proc/75051/io
rchar: 369142
wchar: 17779
syscr: 161
syscw: 13
read_bytes: 16384
write_bytes: 16384
cancelled_write_bytes: 0
```

It should be fairly easy to make psutil robust to this?

**Comment by giampaolo** [comment]
OK, this should fix it: https://github.com/giampaolo/psutil/commit/feeb71389fd5f0e414e6ea8554ab273d296b1b68

**Comment by strubleca** [comment]
This issue still exists even with the commit above. Environment details:

- CentOS 7.4 (`3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`)
- psutil 5.2.2 installed conda; full information (psutil, 5.2.2, py36_0, conda-forge)

**Comment by giampaolo** [comment]
Please paste the output of `/proc/{PID}/io`
