### ISSUE TITLE
Package Perf is no longer available, causes build failure

### ISSUE THREAD

**Issue by SimiCode** [giampaolo/psutil#1587]
**Platform**
* { Linux , Windows}  
* { psutil 5.6.3}

**Bug description**
It seems package Perf is nolonger available
https://pypi.org/project/perf/0.6/

Failing build:  https://ci.appveyor.com/project/giampaolo/psutil/build/job/rllt8x70q20ds50u

```
The last build failed with; 

Collecting perf
  ERROR: Could not find a version that satisfies the requirement perf (from versions: none)
ERROR: No matching distribution found for perf
cmd: C:\Python35-x64\python.exe -m pip install -U coverage flake8 nose pdbpp perf pip pypiwin32 pyreadline setuptools wheel wmi requests
```

**Comment by SimiCode** [comment]
Nosy: @giampaolo @ammaraskar

**Comment by giampaolo** [comment]
Fixed in  55301bd.

**Comment by SimiCode** [comment]
@giampaolo  The build for windows is still failing with the same error.
