### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by landryb** [giampaolo/psutil#562]
Related to #429, i'm working on a basic OpenBSD support in https://github.com/landryb/psutil/tree/openbsd - so far, builds, and passes *some* tests - dunno if you want an early pull request or when it's more complete.... Code copied from FreeBSD, then adapted for OpenBSD.

**Comment by landryb** [comment]
So i've resumed working on this in https://github.com/landryb/psutil/tree/openbsd, merged last changes on master and fixing on top of this.

I used to be able to run the tests but probably after the changes from #578 it fails with version mismatch, while i have no other version of psutils..

```
creating /home/landry/.local/lib/python2.7/site-packages/psutil-3.0.0-py2.7-openbsd-5.6-amd64.egg
Extracting psutil-3.0.0-py2.7-openbsd-5.6-amd64.egg to /home/landry/.local/lib/python2.7/site-packages
psutil 3.0.0 is already the active version in easy-install.pth

Installed /home/landry/.local/lib/python2.7/site-packages/psutil-3.0.0-py2.7-openbsd-5.6-amd64.egg
Processing dependencies for psutil==3.0.0
Finished processing dependencies for psutil==3.0.0
python2.7 test/test_psutil.py
Traceback (most recent call last):
  File "test/test_psutil.py", line 49, in <module>
    import psutil
  File "/home/landry/.local/lib/python2.7/site-packages/psutil-3.0.0-py2.7-openbsd-5.6-amd64.egg/psutil/__init__.py", line 184, in <module>
    raise ImportError(msg)
ImportError: version conflict: '/home/landry/.local/lib/python2.7/site-packages/psutil-3.0.0-py2.7-openbsd-5.6-amd64.egg/psutil/_psutil_bsd.so' C extension module was built for another version of psutil (different than 3.0.0)

```

**Comment by landryb** [comment]
Fixed in 3432cee, now i'm at

```
FAILED (failures=12, errors=34, skipped=67)
```

Which i think isnt so bad. That's what happens when stuff bitrots and isnt merged quickly...

**Comment by landryb** [comment]
And after my last commit in 54fa691, it also works on OpenBSD/i386 (32 bits)

```
FAILED (failures=12, errors=37, skipped=67)
```

**Comment by giampaolo** [comment]
I will not have time to look into this for a while 'cause I'm in US (at least for another month). FWICT 12 failures and 37 errors are still too much. We should try to address if not all at least most of those before including any of this. Also, it looks there's a lot of code in common with FreeBSD. That seems to suggest that the final version of this work will use a single _psutil_bsd.c file with occasional ifdefs here and here, or maybe have _psutil_bsd.c include a new arch/openbsd/platf.c.
When I'll be back to Italy I will install OpenBSD on virtualbox and try to see what I can do. I just wanted to let you know that this is something which will take a while to address on my part.

**Comment by landryb** [comment]
Yeah, same from my side, i wont have time to work on it until july/august. Just wanted to make sure work isnt lost....

**Comment by giampaolo** [comment]
Update here: https://github.com/giampaolo/psutil/pull/615#issuecomment-154474487
