### ISSUE TITLE
psutil.Process.name() sometimes returns truncated process name

### ISSUE THREAD

**Issue by desbma** [giampaolo/psutil#628]
If an exectuable name has a space in it (ie `/tmp/name_start still_name`), `psutil.Process.name()` sometimes returns an incorrectly truncated string.

Reproduced on Linux, see [this glances issue](https://github.com/nicolargo/glances/issues/546) for context.

Code to reproduce on Python 2.7 / 3.X on Linux (gcc needs to be available):

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-

    import os
    import subprocess
    import tempfile

    import psutil

    if __name__ == '__main__':
      # compile a dummy program which loops
      program_filepath = "/tmp/name_start still_name"
      temp_c_filepath = tempfile.mktemp(suffix=".c")
      with open(temp_c_filepath, "wt") as f:
        f.write("void main() { pause(); }")
      cmd = ("gcc", temp_c_filepath, "-o", program_filepath)
      subprocess.check_call(cmd)
      os.remove(temp_c_filepath)

      # run it
      cmd = (program_filepath, "arg1", "arg2")
      process = psutil.Popen(cmd)

      # check
      print("process.exe()", process.exe(), sep="\t")
      print("process.name()", process.name(), sep="\t")

      # cleanup
      process.terminate()
      os.remove(program_filepath)

This outputs :

    process.exe()	/tmp/name_start still_name
    process.name()	name_start

And should output :

    process.exe()	/tmp/name_start still_name
    process.name()	name_start still_name

**Comment by giampaolo** [comment]
Fixed. Thanks a lot for the test case. It saved me some time.

**Comment by desbma** [comment]
Thanks for the quick fix!

**Comment by pseudotensor** [comment]
I still get this in different form:

![image](https://user-images.githubusercontent.com/2249614/47589880-60708300-d91f-11e8-85ff-d382b3716b6d.png)

How to avoid?

**Comment by pseudotensor** [comment]
Yes, the above image shows ps and the bottom part of the image is in pycharm running psutil

**Comment by giampaolo** [comment]
ps shows the command line, not the name. Try `Process().cmdline()` instead.

**Comment by pseudotensor** [comment]
If you see the command above in the screen shot, it's ps -auxwf that shows the process name on the right, not the command line.

**Comment by giampaolo** [comment]
I'm not sure what you consider a bug here. Please note that `name()` is cached after first call so that may conflict with setproctitle.

**Comment by mindojo-victor** [comment]
I have the same issue. `name` is truncated:
```
11662 supervisord
├─ 11203 /home/ubuntu/ap
│ ├─ 11311 Scheduler: brain
│ └─ 11312 Worker-1: brain
├─ 11500 /home/ubuntu/ap
│ ├─ 11570 Scheduler: fast
│ └─ 11571 Worker-1: fast
├─ 11578 /home/ubuntu/ap
└─ 17734 python3
  └─ 10846 gunicorn: maste
    ├─ 10934 gunicorn: worke
    └─ 11202 gunicorn: worke
```
This is what htop shows:
![image](https://user-images.githubusercontent.com/17159503/59552541-14974a80-8f91-11e9-8bfd-37e1aabfdf73.png)
This is the code used:
```python
def print_tree(pid, tree, indent=''):
    try:
        name = psutil.Process(pid).name()
    except psutil.Error:
        name = "?"
    print(pid, name)
    if pid not in tree:
        return
    children = tree[pid][:-1]
    for child in children:
        print(indent + "├─ ", end='')
        print_tree(child, tree, indent + "│ ")
    child = tree[pid][-1]
    print(indent + "└─ ", end='')
    print_tree(child, tree, indent + "  ")


def pstree(pid: int = 0):
    if not pid:
        with open('run/supervisord.pid') as file:
            pid = int(file.read().strip())

    # construct a dict where 'values' are all the processes having 'key' as their parent
    tree = collections.defaultdict(list)
    for p in psutil.process_iter():
        try:
            tree[p.ppid()].append(p.pid)
        except (psutil.NoSuchProcess, psutil.ZombieProcess):
            pass
    # on systems supporting PID 0, PID 0's parent is usually 0
    if 0 in tree and 0 in tree[0]:
        tree[0].remove(0)
    print_tree(pid, tree)
```
